name: cygwin

on:
  push:
    branches: [ workflow-cygwin-cmake ]
  pull_request:

jobs:
  stock:
    name: Stock
    runs-on: windows-latest
    steps:
      - name: Set up prerequisites
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake gcc-g++

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build with CMake/Ninja
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          mkdir build
          cd build
          cmake.exe -D SUPPORT_WINDOWS_FRONTEND=ON -D SUPPORT_BUNDLED_PNG=ON ..
          cmake.exe --build .
