name: msys2

on:
  push:
    branches: [ 'master', 'msys2' ]
  pull_request:

jobs:
  stock:
    name: Stock
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ncurses

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src
          make -f Makefile.msys2 -j$(nproc)

      - name: Build with CMake/Ninja
        run: |
          find "C:\Program Files\Microsoft Visual Studio\2022\EnterpriseC" -print --name 'dumpbin*'
