name: staticsdl2

on:
  push:
    branches: [ workflow-static-sdl2 ]
  pull_request:

jobs:
  sdl:
    name: SDL2
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_mixer

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build with CMake/Ninja
        run: |
          mkdir build
          cd build
          env LDFLAGS="-static -lSDL2 -lSDL2_ttf -lSDL2_image -ltiff -ljbig -lLerc -lzstd -llzma -ljxl -lhwy -lavif -laom -ldav1d -lrav1e -lSvtAv1Enc -lyuv -lwebp -lwebpdemux -lsharpyuv -lfreetype -lharfbuzz -lDwrite -lfreetype -lbrotlidec -lbrotlicommon -lgraphite2 -lpng -ldeflate -ljpeg -lbz2 -lintl -lrpcrt4 -lz -lVersion -lstdc++ -lImm32 -lhid -lsetupapi -lole32 -loleaut32 -lSDL2_mixer -lflac -lopusfile -lopus -lvorbisfile -lvorbis -logg -lshlwapi -lwavpack -lxmp -lwinmm -lntdll" cmake -G Ninja -DSUPPORT_SDL2_FRONTEND=ON ..
          ninja -j$(nproc)
